# Generated by Django 3.0.6 on 2020-06-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200602_2321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
