# Generated by Django 3.0.6 on 2020-06-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
    ]
